# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(["psfexPsf",
                                  "psf",
                                  "field",
                                  "prefs"], addUnderscore=False)
